// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgqNqe94w7gwo_8qM_BxFoS4NFlF1DZfc',
    appId: '1:668367919669:web:6eecf098453b50e8c1af7c',
    messagingSenderId: '668367919669',
    projectId: 'palp-uts-22100032',
    authDomain: 'palp-uts-22100032.firebaseapp.com',
    storageBucket: 'palp-uts-22100032.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWbkSDFdwC4dy_z3AUkisOELPETz9r7Tg',
    appId: '1:668367919669:android:09ba92c01f10a9b7c1af7c',
    messagingSenderId: '668367919669',
    projectId: 'palp-uts-22100032',
    storageBucket: 'palp-uts-22100032.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuq6aOT527lTQgm10bUClxkUsPfJwOnvU',
    appId: '1:668367919669:ios:c13207c99e8907a7c1af7c',
    messagingSenderId: '668367919669',
    projectId: 'palp-uts-22100032',
    storageBucket: 'palp-uts-22100032.firebasestorage.app',
    iosBundleId: 'com.example.utsPalp202522100032',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuq6aOT527lTQgm10bUClxkUsPfJwOnvU',
    appId: '1:668367919669:ios:c13207c99e8907a7c1af7c',
    messagingSenderId: '668367919669',
    projectId: 'palp-uts-22100032',
    storageBucket: 'palp-uts-22100032.firebasestorage.app',
    iosBundleId: 'com.example.utsPalp202522100032',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgqNqe94w7gwo_8qM_BxFoS4NFlF1DZfc',
    appId: '1:668367919669:web:ca6e6616fffdbe95c1af7c',
    messagingSenderId: '668367919669',
    projectId: 'palp-uts-22100032',
    authDomain: 'palp-uts-22100032.firebaseapp.com',
    storageBucket: 'palp-uts-22100032.firebasestorage.app',
  );

}